-- 岗位工作登记表
CREATE TABLE IF NOT EXISTS position_work_logs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL COMMENT '用户ID',
    user_name VARCHAR(50) COMMENT '用户姓名',
    station_id INT COMMENT '场站ID',
    station_name VARCHAR(100) COMMENT '场站名称',
    position_name VARCHAR(50) COMMENT '岗位名称',
    position_job_id INT COMMENT '关联岗位工作项目ID',
    work_date DATE NOT NULL COMMENT '工作日期',
    work_name VARCHAR(200) NOT NULL COMMENT '工作项目名称',
    standard_hours DECIMAL(5,2) DEFAULT 0 COMMENT '标准工时(小时)',
    actual_hours DECIMAL(5,2) DEFAULT 0 COMMENT '实际工时(小时)',
    is_completed TINYINT DEFAULT 0 COMMENT '是否完成：0未完成 1已完成',
    progress INT DEFAULT 0 COMMENT '完成进度 0-100',
    remark TEXT COMMENT '备注',
    is_overtime TINYINT DEFAULT 0 COMMENT '是否超时',
    appeal_status VARCHAR(20) COMMENT '申诉状态：pending待审批, approved已通过, rejected已驳回',
    appeal_reason TEXT COMMENT '申诉原因',
    appeal_time DATETIME COMMENT '申诉时间',
    approver_id INT COMMENT '审批人ID',
    approver_name VARCHAR(50) COMMENT '审批人姓名',
    approve_time DATETIME COMMENT '审批时间',
    approve_remark TEXT COMMENT '审批备注',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_date (user_id, work_date),
    INDEX idx_station (station_id),
    INDEX idx_appeal_status (appeal_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='岗位工作登记表';
