SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS maintenance_records (
  id INT PRIMARY KEY AUTO_INCREMENT,
  record_code VARCHAR(50) NOT NULL UNIQUE,
  plan_id INT,
  project_id INT NOT NULL,
  station_id INT,
  equipment_name VARCHAR(100) NOT NULL,
  equipment_code VARCHAR(50),
  maintenance_date DATE NOT NULL,
  maintainer_id INT NOT NULL,
  maintainer_name VARCHAR(50),
  maintenance_content TEXT,
  result ENUM('normal', 'found_issue') DEFAULT 'normal',
  issue_description TEXT,
  handling_measures TEXT,
  photo_urls TEXT,
  work_hours DECIMAL(4,2),
  status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  reviewer_id INT,
  reviewer_name VARCHAR(50),
  review_time DATETIME,
  reject_reason TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_maintenance_plan (plan_id),
  INDEX idx_maintenance_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS repair_records (
  id INT PRIMARY KEY AUTO_INCREMENT,
  record_code VARCHAR(50) UNIQUE,
  fault_report_id INT NOT NULL,
  project_id INT NOT NULL,
  station_id INT,
  equipment_code VARCHAR(50),
  equipment_name VARCHAR(100),
  equipment_location VARCHAR(200),
  equipment_model VARCHAR(100),
  fault_date DATE,
  fault_time TIME,
  fault_description TEXT,
  preliminary_judgment TEXT,
  reporter_id INT,
  reporter_name VARCHAR(50),
  report_date DATE,
  report_time TIME,
  repair_person_id INT,
  repair_person_name VARCHAR(50),
  repair_start_date DATE,
  repair_start_time TIME,
  repair_end_date DATE,
  repair_end_time TIME,
  repair_content TEXT,
  repair_tools TEXT,
  consumables_list JSON,
  consumables_total DECIMAL(10,2) DEFAULT 0,
  parts_list JSON,
  parts_total DECIMAL(10,2) DEFAULT 0,
  repair_result ENUM('normal', 'observe', 'unsolved'),
  observe_days INT,
  unsolved_reason TEXT,
  verifier_id INT,
  verifier_name VARCHAR(50),
  verify_date DATE,
  verify_time TIME,
  verify_result ENUM('pass', 'fail'),
  verify_comment TEXT,
  rating INT,
  rating_comment TEXT,
  archivist VARCHAR(50),
  archive_dept VARCHAR(50),
  archive_date DATE,
  status ENUM('draft_report', 'submitted_report', 'dispatched', 'repairing', 'repaired_submitted', 'accepted', 'archived') DEFAULT 'draft_report',
  dispatch_by INT,
  dispatch_by_name VARCHAR(50),
  dispatch_date DATE,
  dispatch_time TIME,
  dispatch_remark TEXT,
  work_hours DECIMAL(5,1),
  created_by INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_repair_fault_report (fault_report_id),
  INDEX idx_repair_person (repair_person_id),
  INDEX idx_repair_status (status),
  INDEX idx_repair_project_station (project_id, station_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS material_requisitions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  requisition_code VARCHAR(50) NOT NULL UNIQUE,
  repair_record_id INT,
  applicant_id INT NOT NULL,
  applicant_name VARCHAR(50),
  material_list JSON NOT NULL,
  total_amount DECIMAL(10,2),
  status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  approver_id INT,
  approver_name VARCHAR(50),
  approve_time DATETIME,
  reject_reason TEXT,
  project_id INT NOT NULL,
  station_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_requisition_status (status),
  INDEX idx_requisition_applicant (applicant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS safety_hazard_inspections (
  id INT PRIMARY KEY AUTO_INCREMENT,
  record_code VARCHAR(50) NOT NULL UNIQUE,
  inspection_date DATE NOT NULL,
  station_name VARCHAR(100) NOT NULL,
  station_type VARCHAR(50),
  hazard_category ENUM('电气', '违规违纪', '标识', '基础设施', '环境卫生', '机械设备', '特种作业', '制度文件', '消防', '特种设备') NOT NULL,
  is_first_found ENUM('是', '二次', '否') NOT NULL,
  hazard_description TEXT,
  photo_urls TEXT,
  location VARCHAR(200),
  handler_id INT,
  handler_name VARCHAR(50),
  inspector_id INT NOT NULL,
  inspector_name VARCHAR(50),
  status ENUM('pending', 'processing', 'completed') DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_hazard_station (station_name),
  INDEX idx_hazard_date (inspection_date),
  INDEX idx_hazard_inspector (inspector_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS safety_rectifications (
  id INT PRIMARY KEY AUTO_INCREMENT,
  record_code VARCHAR(50) NOT NULL UNIQUE,
  inspection_id INT NOT NULL,
  root_cause ENUM('人的不安全行为', '物的不安全状态', '职责不清', '人岗匹配', '工作流程', '工作标准', '工作执行', '设计缺陷', '劳动防护用品配备不足', '安全设施建设投入不足') NOT NULL,
  rectification_measures TEXT NOT NULL,
  responsible_person_id INT NOT NULL,
  responsible_person_name VARCHAR(50),
  punished_person_id INT,
  punished_person_name VARCHAR(50),
  punishment_result TEXT,
  is_completed ENUM('是', '否') NOT NULL,
  completion_photos TEXT,
  root_cause_category ENUM('组织措施', '管理措施', '技术措施', '经济措施'),
  status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  approver_id INT,
  approver_name VARCHAR(50),
  approve_time DATETIME,
  approve_comment TEXT,
  reject_reason TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_rectification_inspection (inspection_id),
  INDEX idx_rectification_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
