CREATE TABLE IF NOT EXISTS plc_scale_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  record_code VARCHAR(50) NOT NULL UNIQUE,
  scale_id VARCHAR(50) DEFAULT NULL,
  station_id INT DEFAULT NULL,
  weight_time DATETIME DEFAULT NULL,
  vehicle_no VARCHAR(50) DEFAULT NULL,
  material VARCHAR(100) DEFAULT NULL,
  weight_gross DECIMAL(10,2) DEFAULT NULL,
  weight_tare DECIMAL(10,2) DEFAULT NULL,
  weight_net DECIMAL(10,2) DEFAULT NULL,
  operator_name VARCHAR(50) DEFAULT NULL,
  status VARCHAR(20) DEFAULT NULL,
  source VARCHAR(20) NOT NULL DEFAULT 'http',
  file_name VARCHAR(255) DEFAULT NULL,
  raw_payload TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_plc_scale_id (scale_id),
  INDEX idx_plc_station_id (station_id),
  INDEX idx_plc_weight_time (weight_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS plc_file_imports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  file_key VARCHAR(255) NOT NULL UNIQUE,
  status VARCHAR(20) NOT NULL DEFAULT 'processed',
  error_message TEXT DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
